name: Deploy All Live

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, chrome, firefox]

    steps:
    - uses: actions/checkout@v3
      with:
        repository: dont-code/plugins
        path: plugins
        fetch-depth: 0
        ref: ${{inputs.branch}}
        token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
    - name: Setup build environment
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    - run: |
        npm install -g nx
    - name: Building Plugins
      run: |
        npm install --force
        npm install @dontcode/core@latest --no-optional
        nx run basic:build:production
        nx run basic:test
        nx run fields:build:production
        nx run fields:test
        nx run screen:build:production
        nx run screen:test
      working-directory: 'plugins'
    - run: |
        nx run plugin-tester-e2e:e2e --browser ${{matrix.browser}}
      working-directory: 'plugins'
    - uses: actions/upload-artifact@v3
      # Test run screenshots only on failure
      if: failure()
      with:
        name: cypress-screenshots
        path: plugins/dist/cypress/apps/plugin-tester-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: plugins/dist/cypress/apps/plugin-tester-e2e/videos
    - name: Prepare Plugins deployment
      run: nx run plugin-tester:build:production --base-href "https://dont-code.net/plugins/"
      working-directory: 'plugins'
    - name: Building Plugin Seed
      uses: actions/checkout@v3
      with:
        repository: dont-code/plugin-seed
        path: plugin-seed
        fetch-depth: 0
        ref: ${{inputs.branch}}
        token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
    - run: |
        npm install --force
        npm install @dontcode/core@latest @dontcode/plugin-common@latest @dontcode/sandbox@latest
        nx run seed:build:production
        nx run seed:test
        nx run seed-tester:test
      working-directory: 'plugin-seed'
    - run: |
        nx run seed-tester-e2e:e2e --browser ${{matrix.browser}}
      working-directory: 'plugin-seed'
    - uses: actions/upload-artifact@v3
      # Test run screenshots only on failure
      if: failure()
      with:
        name: cypress-screenshots
        path: plugin-seed/dist/cypress/apps/seed-tester-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: plugin-seed/dist/cypress/apps/seed-tester-e2e/videos
    - name: Prepare Plugin Seed Deployment
      run:  nx run seed-tester:build:production --base-href "https://dont-code.net/plugin-seed/"
      working-directory: 'plugin-seed'

    - name: Building Plugin Rest
      uses: actions/checkout@v3
      with:
        repository: dont-code/plugin-rest
        path: plugin-rest
        fetch-depth: 0
        ref: ${{inputs.branch}}
        token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}

    - run: |
        npm install --force
        npm install @dontcode/core@latest @dontcode/plugin-common@latest @dontcode/sandbox@latest
        nx run rest:build:production
        nx run rest:test
        nx run rest-tester:test
      working-directory: 'plugin-rest'
    - run: |
        nx run rest-tester-e2e:e2e --browser ${{matrix.browser}}
      working-directory: 'plugin-rest'
    - uses: actions/upload-artifact@v3
      # Test run screenshots only on failure
      if: failure()
      with:
        name: cypress-screenshots
        path: plugin-rest/dist/cypress/apps/rest-tester-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: plugin-rest/dist/cypress/apps/rest-tester-e2e/videos
    - name: Prepare Plugin Rest deployment
      run: nx run rest-tester:build:production --base-href "https://dont-code.net/plugin-rest/"
      working-directory: 'plugin-rest'

    - name: Building Plugin Report
      run: |
        npm install --force
        npm install ../core/node/dontcode-core-${{inputs.version}}.tgz ../plugins/dontcode-plugin-common-${{inputs.version}}.tgz ../plugins/dontcode-sandbox-${{inputs.version}}.tgz ../plugins/dontcode-plugin-basic-${{inputs.version}}.tgz ../plugins/dontcode-plugin-fields-${{inputs.version}}.tgz
        nx run report:build:production
        nx run report:test
        nx run report-tester:test
      working-directory: 'plugin-report'
    - run: |
        nx run report-tester-e2e:e2e --browser chromium
        nx run report-tester-e2e:e2e --browser chrome
      working-directory: 'plugin-report'
    - uses: actions/upload-artifact@v3
      # Test run screenshots only on failure
      if: failure()
      with:
        name: cypress-screenshots
        path: plugin-report/dist/cypress/apps/report-tester-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: plugin-report/dist/cypress/apps/report-tester-e2e/videos

    - name: Building Plugin Report
      uses: actions/checkout@v3
      with:
        repository: dont-code/plugin-report
        path: plugin-report
        fetch-depth: 0
        ref: ${{inputs.branch}}
        token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
    - run: |
        npm install --force
        npm install @dontcode/core@latest @dontcode/plugin-common@latest @dontcode/sandbox@latest @dontcode/plugin-basic@latest @dontcode/plugin-fields@latest        nx run report:build:production
        nx run report:test
        nx run report-tester:test
      working-directory: 'plugin-report'
    - run: |
        nx run report-tester-e2e:e2e --browser ${{matrix.browser}}
      working-directory: 'plugin-report'
    - uses: actions/upload-artifact@v3
      # Test run screenshots only on failure
      if: failure()
      with:
        name: cypress-screenshots
        path: plugin-report/dist/cypress/apps/report-tester-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: plugin-report/dist/cypress/apps/report-tester-e2e/videos
    - name: Prepare Plugin Report Deployment
      run:  nx run report-tester:build:production --base-href "https://dont-code.net/plugin-report/"
      working-directory: 'plugin-report'

    - name: Building Plugin Commerce
      uses: actions/checkout@v3
      with:
        repository: dont-code/plugin-commerce
        path: plugin-commerce
        fetch-depth: 0
        ref: ${{inputs.branch}}
        token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
    - run: |
        npm install --force
        npm install @dontcode/core@latest @dontcode/plugin-common@latest @dontcode/sandbox@latest @dontcode/plugin-basic@latest @dontcode/plugin-fields@latest
        nx run commerce:build:production
        nx run commerce:test
        nx run commerce-tester:test
      working-directory: 'plugin-commerce'
    - run: |
        nx run commerce-tester-e2e:e2e --browser ${{matrix.browser}}
      working-directory: 'plugin-commerce'
    - uses: actions/upload-artifact@v3
      # Test run screenshots only on failure
      if: failure()
      with:
        name: cypress-screenshots
        path: plugin-commerce/dist/cypress/apps/commerce-tester-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: plugin-commerce/dist/cypress/apps/commerce-tester-e2e/videos
    - name: Prepare Plugin Commerce deployment
      run:  nx run commerce-tester:build:production --base-href "https://dont-code.net/plugin-commerce/"
      working-directory: 'plugin-commerce'

    - name: Building IDE Builder
      uses: actions/checkout@v3
      with:
        repository: dont-code/ide-ui
        path: ide-ui
        fetch-depth: 0
        ref: ${{inputs.branch}}
        token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
    - run: |
        npm install --force
        npm install @dontcode/core@latest @dontcode/plugin-common@latest @dontcode/sandbox@latest @dontcode/plugin-basic@latest @dontcode/plugin-fields@latest @dontcode/plugin-screen@latest @dontcode/plugin-rest@latest @dontcode/plugin-report@latest @dontcode/plugin-commerce@latest
        nx run ide-ui:build:production
        nx run ide-ui:test
      working-directory: 'ide-ui'
    - run: |
        nx run ide-ui-e2e:e2e --browser ${{matrix.browser}}
      working-directory: 'ide-ui'
    - uses: actions/upload-artifact@v3
      # Test run screenshots only on failure
      if: failure()
      with:
        name: cypress-screenshots
        path: ide-ui/dist/cypress/apps/ide-ui-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: ide-ui/dist/cypress/apps/ide-ui-e2e/videos
    - name: Prepare IDE Builder deployment
      run: nx run ide-ui:build:production --base-href "https://dont-code.net/ide-ui/"
      working-directory: 'ide-ui'

    - name: Building Previewer
      uses: actions/checkout@v3
      with:
        repository: dont-code/preview-ui
        path: preview-ui
        fetch-depth: 0
        ref: ${{inputs.branch}}
        token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
    - run: |
        npm install --force
        npm install @dontcode/core@latest @dontcode/plugin-common@latest @dontcode/sandbox@latest
        nx run preview-ui:build:production
      working-directory: 'preview-ui'
    - run: |
        nx run preview-ui-e2e:e2e --browser ${{matrix.browser}}
      working-directory: 'preview-ui'
    - uses: actions/upload-artifact@v3
      # Test run screenshots only on failure
      if: failure()
      with:
        name: cypress-screenshots
        path: preview-ui/dist/cypress/apps/preview-ui-e2e/screenshots
        # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: preview-ui/dist/cypress/apps/preview-ui-e2e/videos
    - name: Prepare Previewer deployment
      run: nx run preview-ui:build:production --base-href "https://dont-code.net/preview-ui/"
      working-directory: 'preview-ui'

    - name: Deploy everything to Live
      if: ${{ success() }}
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        repo: dont-code/plugins
        target_branch: gh-pages # The branch the action should deploy to.
        build_dir: plugins/dist/apps/plugin-tester
        jekyll: false
      env:
        GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
    - if: ${{ success() }}
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        repo: dont-code/plugin-seed
        target_branch: gh-pages # The branch the action should deploy to.
        build_dir: plugin-seed/dist/apps/seed-tester
        jekyll: false
      env:
        GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
    - if: ${{ success() }}
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        repo: dont-code/plugin-rest
        target_branch: gh-pages # The branch the action should deploy to.
        build_dir: plugin-rest/dist/apps/rest-tester
        jekyll: false
      env:
        GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
    - if: ${{ success() }}
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        repo: dont-code/plugin-report
        target_branch: gh-pages # The branch the action should deploy to.
        build_dir: plugin-report/dist/apps/report-tester
        jekyll: false
      env:
        GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
    - if: ${{ success() }}
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        repo: dont-code/plugin-commerce
        target_branch: gh-pages # The branch the action should deploy to.
        build_dir: plugin-commerce/dist/apps/commerce-tester
        jekyll: false
      env:
        GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
    - if: ${{ success() }}
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        repo: dont-code/ide-ui
        target_branch: gh-pages # The branch the action should deploy to.
        build_dir: ide-ui/dist/apps/ide-ui
        jekyll: false
      env:
        GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
    - if: ${{ success() }}
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        repo: dont-code/preview-ui
        target_branch: gh-pages # The branch the action should deploy to.
        build_dir: preview-ui/dist/apps/preview-ui
        jekyll: false
      env:
        GITHUB_TOKEN: ${{secrets.DONTCODE_ACTIONS_TOKEN }}
