name: Dont-code Services release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the release
        required: true
        type: string
      branch:
        description: The branch to use. Only main is deployed
        required: false
        default: Development
        type: choice
        options:
        - Development
        - main

jobs:
  build-common:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout common repositories
      uses: actions/checkout@v3
      with:
        repository: dont-code/core
        path: core
        fetch-depth: 0
        ref: main
    - uses: actions/checkout@v3
      with:
        repository: dont-code/common-quarkus-mongo
        path: common-quarkus-mongo
        fetch-depth: 0
        ref: main
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'adopt'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
    - name: Build
      run: mvn --batch-mode --update-snapshots install
      working-directory: core/java
      env:
        MAVEN_GPG_PASSPHRASE: ${{secrets.MAVEN_GPG_PASSPHRASE}}
    - run: mvn --batch-mode --update-snapshots install
      working-directory: common-quarkus-mongo
      env:
        MAVEN_GPG_PASSPHRASE: ${{secrets.MAVEN_GPG_PASSPHRASE}}

  build-ide-services:
    runs-on: ubuntu-latest
    needs: build-common

    steps:
    - uses: actions/checkout@v3
      with:
        repository: dont-code/ide-services
        path: ide-services
        fetch-depth: 0
        ref: main
    - name: Build
      run: mvn --batch-mode --update-snapshots install
      working-directory: ide-services
      env:
        MAVEN_GPG_PASSPHRASE: ${{secrets.MAVEN_GPG_PASSPHRASE}}

  build-preview-services:
    runs-on: ubuntu-latest
    needs: build-common

    steps:
    - uses: actions/checkout@v3
      with:
        repository: dont-code/preview-services
        path: preview-services
        fetch-depth: 0
        ref: main
    - name: Build
      run: mvn --batch-mode --update-snapshots install
      working-directory: data-services
      env:
        MAVEN_GPG_PASSPHRASE: ${{secrets.MAVEN_GPG_PASSPHRASE}}

  build-data-services:
    runs-on: ubuntu-latest
    needs: build-common

    steps:
    - uses: actions/checkout@v3
      with:
        repository: dont-code/data-services
        path: data-services
        fetch-depth: 0
        ref: main
    - name: Build
      run: mvn --batch-mode --update-snapshots install
      working-directory: data-services
      env:
        MAVEN_GPG_PASSPHRASE: ${{secrets.MAVEN_GPG_PASSPHRASE}}

  build-project-services:
    runs-on: ubuntu-latest
    needs: build-common

    steps:
    - uses: actions/checkout@v3
      with:
        repository: dont-code/project-services
        path: project-services
        fetch-depth: 0
        ref: main
    - name: Build
      run: mvn --batch-mode --update-snapshots install
      working-directory: data-services
      env:
        MAVEN_GPG_PASSPHRASE: ${{secrets.MAVEN_GPG_PASSPHRASE}}
