name: Dont-code Services release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the release
        required: true
        type: string
      branch:
        description: The branch to use. Only main is deployed
        required: false
        default: Development
        type: choice
        options:
        - Development
        - main

jobs:
  build-common:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout common repositories
      uses: actions/checkout@v3
      with:
        repository: dont-code/core
        path: core
        fetch-depth: 0
        ref: main
    - uses: actions/checkout@v3
      with:
        repository: dont-code/common-quarkus-mongo
        path: common-quarkus-mongo
        fetch-depth: 0
        ref: main
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build
      run: mvn --batch-mode --update-snapshots install
      working-directory: core
    - run: mvn --batch-mode --update-snapshots install
      working-directory: common-quarkus-mongo

  build-ide-services:
    runs-on: ubuntu-latest
    needs: build-common

    steps:
    - uses: actions/checkout@v3
      with:
        repository: dont-code/ide-services
        path: ide-services
        fetch-depth: 0
        ref: main
    - name: Build
      run: mvn --batch-mode --update-snapshots install
      working-directory: ide-services

  build-preview-services:
    runs-on: ubuntu-latest
    needs: build-common

    steps:
    - uses: actions/checkout@v3
      with:
        repository: dont-code/preview-services
        path: preview-services
        fetch-depth: 0
        ref: main
    - name: Build
      run: mvn --batch-mode --update-snapshots install
      working-directory: data-services

  build-data-services:
    runs-on: ubuntu-latest
    needs: build-common

    steps:
      - uses: actions/checkout@v3
        with:
          repository: dont-code/data-services
          path: data-services
          fetch-depth: 0
          ref: main
      - name: Build
        run: mvn --batch-mode --update-snapshots install
        working-directory: data-services

  build-project-services:
    runs-on: ubuntu-latest
    needs: build-common

    steps:
      - uses: actions/checkout@v3
        with:
          repository: dont-code/project-services
          path: project-services
          fetch-depth: 0
          ref: main
      - name: Build
        run: mvn --batch-mode --update-snapshots install
        working-directory: data-services
